name: Reveille
pygments: true
relative_permalinks: false

markdown: redcarpet

exclude: [ 
  'script', 'vendor', 'config.ru', 'Gemfile*', 'Guardfile', 'bin', 'unicorn.rb', 'Procfile'
]

assets:
  # compress:
    # js: uglifier
    # css: sass
    
  cachebust: soft